### ISSUE TITLE
Курсовой проект - 9 семестр

### ISSUE THREAD

**Issue by kstrizhov** [kstrizhov/kstrizhov.github.io#1]
@aurusov

Создал таску, здесь скорее всего будет удобнее всего обсуждать. Залил все, что есть, в репозиторий, с github pages чуть позже разберусь.

По почте сейчас еще продублирую, а то с гитхаба неудобно смотреть.

Делаю лист с результатами, по записке пока только оглавление.

**Comment by kstrizhov** [comment]
Добавил лист результатов работы.

**Comment by aurusov** [comment]
Уж лучше с pages разберись. Это быстро, а смотреть удобно. Вот пример https://github.com/bogachev-pa/bogachev-pa.github.io/issues/1

**Comment by aurusov** [comment]
И в общемто-то разбираться нечего. Вот пример твоего листа http://kstrizhov.github.io/lists/a1_activity_diagram_2.pdf. Переименуй файлы в формат `Номер_листа-Название-Формат`

**Comment by kstrizhov** [comment]
Сделал pages с материалами курсового.
http://kstrizhov.github.io

Лист 1 - Постановка задачи - А1
http://kstrizhov.github.io/lists/1_postanovka_zadachi_a1.pdf

Лист 2 - Диаграмма классов - А1
http://kstrizhov.github.io/lists/2_diagramma_classov_a1.pdf

Лист 3 - Диаграмма компонентов - А2
http://kstrizhov.github.io/lists/3_component_diagram_a2.pdf

Лист 4 - Диаграмма деятельности - часть lib (чтение бинарной сериализации, формирование древовидной структуры) - А1
http://kstrizhov.github.io/lists/4_diagramma_deyatelnosti_libpart_a1.pdf

Лист 5 - Диаграмма деятельности - часть ui (вызов графа из окна трассировки) - А2
http://kstrizhov.github.io/lists/5_diagramma_deyatelnosti_uipart_a2.pdf

Лист 6 - Результаты работы - А1
http://kstrizhov.github.io/lists/6_results_a1.pdf

Итого 5 листов А1.

Записка
http://kstrizhov.github.io/report_pdf.pdf
http://kstrizhov.github.io/report.docx

**Comment by aurusov** [comment]
:one: `А1` Постановка задачи <b>[на печать]</b>

:two: `А1` Диаграмма классов подсистемы визуализации поиска на графе пространства состояний <b>[на печать]</b>

:three: `А2` Диаграмма компонентов подсистемы визуализации поиска на графе пространства состояний <b>[на печать]</b>

:four: `А1` Диаграмма деятельности чтения данных бинарной сериализации <b>[на печать]</b>

:five: `А2` Диаграмма деятельности вызова модуля визуализации из окна трассировки <b>[на печать]</b>

:six: `А1` Результаты работы <b>[на печать]</b>

:seven: Штампы для плакатов <b>[на печать]</b>

:book: Записка <b>[на печать]</b>

**Comment by aurusov** [comment]
Предлагаю добавить [диаграмму компонентов](https://ru.wikipedia.org/wiki/%D0%94%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2). Формат А2-А3. На ней можно показать все используемые библиотеки, как ребят, так и для отрисовки графа.

**Comment by kstrizhov** [comment]
По поводу третьего листа, согласен, места много, но на А2 я пробовал размещать, мелко получается, будет плохо видно.

По поводу кликов по трассировке, да, сейчас двойной клик мышью по любой строке, относящейся к трассировке DPT вызывает окно графа для соответствующей точки принятия решений.

Вызов нескольких окон для разных точек принятия решений в модели работает, он не совсем доделан в плане продуктового решения, но уже сейчас можно пользоваться и получать корректный результат.

> Сделай скриншоты еще больше, чтобы он стали минимум как А3 

Если они будут как А3, то они будут занимать ровно 1/4 листа, разве нет? Как их тогда размещать? 

PS А в чем Вы рисовали стрелки и прочую графику на листах?

**Comment by aurusov** [comment]
> Если они будут как А3, то они будут занимать ровно 1/4 листа, разве нет? Как их тогда размещать?

Каждый сделать больше, как минимум по А3. Т.е. два скрина в сумме должны занимать половину листа.

> А в чем Вы рисовали стрелки и прочую графику на листах?

Поставил Я.Диск. У него есть редактор скриншотов: https://disk.yandex.ru/screenshot/

**Comment by kstrizhov** [comment]
Дописал текст записки. Осталось пронумеровать содержание и вставить список литературы. Хотелось бы Ваших комментариев, особенно на счет главы с выбором библиотеки, на наличие бреда и ошибок.

**Comment by kstrizhov** [comment]
Выложил финальный вариант записки, все доделал. Решил добавить в список терминов слушателя, который listener, чтобы по тексту не писать его везде в кавычках. Правильно ли я его назвал, или есть какой-то устоявшийся термин?

**Comment by aurusov** [comment]
> Правильно ли я его назвал, или есть какой-то устоявшийся термин?

Есть
https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%B1%D0%BB%D1%8E%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C_%28%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%29

Тот, кто слушает, называется подписчик.

**Comment by aurusov** [comment]
> Хотелось бы Ваших комментариев, особенно на счет главы с выбором библиотеки, на наличие бреда и ошибок.

Насчет формальных ошибок не скажу, т.к. не делал обзор. Выглядит вполне нормально.

**Comment by aurusov** [comment]
Посмотрел листы и записку, обновил итого.

**Comment by kstrizhov** [comment]
Сделал лист с диаграммой компонентов, но есть вопросы:
1. Вынес только те компоненты, которые затрагивают подсистему визуализации. По идее это не диаграмма компонентов RAO-XT, но и не диаграмма самой подсистемы, там вперемешку. Как назвать диаграмму?
2. Или лучше сделать диаграмму всей RAO-XT, но тогда что выносить на лист, а что оставить за бортом, потому что там много всяких компонентов типа хэндлеров и xtext-овских файлов.
3. Правильно ли я сделал связь JGraphx и Swing? Я подумал что там должна быть композиция, потому что jgrapx является расширением swing.

**Comment by kstrizhov** [comment]
> что значит Корректно ? Как проверить, насколько корректно ?

Корректно, значит выводит именно то, что было сериализовано. Проверить - сравнить цифры с теми, что выводит трассировка (считается, что она все выводит правильно).

> на каком количестве разных моделей проходило тестирование ?

По факту на одной, игра 5, с разными изменениями, которые описаны в методике (п. 7.1. в записке)

> где можно почитать про методику ?

Пункт 7.1. записки.

> Меня смущает свободное место сверху и снизу листа. Не сильно, но смущает. Ты мог бы увеличить размер шрифта и заполнить лист по высоте ?

Попробую, но мне кажется в таком случае все элементы пропорционально увеличатся, что в целом приведет к масштабированию диаграммы. Тут скорее надо играть с размерами самих прямоугольников всех классов.

> Так намного лучше, но таже проблема, что и у второго листа. И такой же минорный приоритет. Но тут вообще непонятно как растянуть во вертикале. Есть мыли ?

Тут мне кажется точно будет сложнее, эту схему вообще долго масшатбировал и менял размеры элеменов, чтобы подходила по форме к формату листа и в то же время не было больших пустых мест между элементами.

**Comment by kstrizhov** [comment]
Переделал 5 лист

**Comment by aurusov** [comment]
> Корректно, значит...

Хорошо, не забудь про это на защите, а то слово режет слух

> По факту на одной, игра 5...

Так и напиши в записке

> Пункт 7.1. записки.

Тоже, что и с корректно

> Попробую, но мне кажется в таком случае все элементы пропорционально увеличатся, что в целом приведет к масштабированию диаграммы. Тут скорее надо играть с размерами самих прямоугольников всех классов.

Да, именно попробуй. Не получится - оставим так. Но попробовать стоит. Тоже и к другому листу.

**Comment by aurusov** [comment]
Обновил итого. Проверь ссылки на листы в https://github.com/kstrizhov/kstrizhov.github.io/issues/1#issuecomment-70330302

**Comment by kstrizhov** [comment]
Обновил ссылки на листы.

Исправил ссылки на список литературы в записке. 

Исправил про модели в пункте "контроль и приемка".

> Что-то не припомню значка композиции на диаграммах компонентов. Ты его просто взял с диаграммы классов ?

Visual Paradigm дает возможность рисовать ее на дигарамме компонентов. Вроде как достаточно продвинутое CASE-средство. Поэтому подумал, что так будет вернее. Но могу исправить на стандартную стрелочку.

> Он сейчас в каком формате ?

В формате А2.

Размер шрифта для вставок кода в записке тоже поправил.

**Comment by kstrizhov** [comment]
Переделал 1 и 6 листы.

**Comment by kstrizhov** [comment]
Переделал 3 лист.

**Comment by aurusov** [comment]
> Поэтому подумал, что так будет вернее. Но могу исправить на стандартную стрелочку.

Не надо

**Comment by aurusov** [comment]
Обновил итого

**Comment by aurusov** [comment]
Жду ответов/изменений/решений по всем незавершенным пунктам.

**Comment by aurusov** [comment]
Обновил итого, всё можно на печать.
Замечание: в штампах ты указал наши фамилии без инициалов. Я готов такое подписать. Но привычнее, когда инициалы указаны. Если будет возможность - исправь до печати и перевыложи на гитхаб.

**Comment by kstrizhov** [comment]
> в штампах ты указал наши фамилии без инициалов

Исправлю.

 Хотел спросить по поводу титульников и задания на проект, его надо вручную заполнять, или набивать?

И титульный должен называться "Расчетно-пояснительная записка"? Где-то на 3м курсе еще говорили, что по новым стандартам просто "Пояснительная записка"

**Comment by aurusov** [comment]
> Хотел спросить по поводу титульников и задания на проект, его надо вручную заполнять, или набивать?

Обычно вручную. Мне кажется, что это неважно.

> И титульный должен называться "Расчетно-пояснительная записка"?

Не понял, где это ? Ты не путаешь с полем для темы ?

**Comment by kstrizhov** [comment]
Вот здесь
![2015-01-30 17-24-54 rpz-titulnik doc - microsoft word 2](https://cloud.githubusercontent.com/assets/9355661/5982778/bde9fb64-a8d7-11e4-9108-173d6b497641.png)

Я про название этого титульного. Слышал где-то, что должно быть просто "пояснительная записка", то ли на тмм, то ли на детмаше.

**Comment by aurusov** [comment]
Все равно не понимаю. Выдели как-то на рисунке область, про которую говоришь.

**Comment by kstrizhov** [comment]
Выделил.
