### ISSUE TITLE
Курсовой проект - 10 семестр

### ISSUE THREAD

**Issue by kstrizhov** [kstrizhov/kstrizhov.github.io#2]
Создал таску для ообсуждения проекта этого семестра.

Все материалы находятся тут (буду обновлять по необходимости):
http://kstrizhov.github.io/

Записка в формате `.docx`:
http://kstrizhov.github.io/10sem/zapiska_10sem.docx

Записка в формате `.pdf`:
http://kstrizhov.github.io/10sem/zapiska_10sem.pdf

Лист 1 - Постановка задачи - А1
http://kstrizhov.github.io/10sem/1_postanovka_zadachi_a1.pdf

Лист 2 - Диаграмма классов подсистемы визуализации поиска на графе пространства состояний - А1
http://kstrizhov.github.io/10sem/2_diagramma_classov_a1.pdf

Лист 3 - Диаграмма последовательности работы подсистемы визуализации поиска на графе пространства состояний - А1
http://kstrizhov.github.io/10sem/3_diagramma_posledovatelnosti_a1.pdf

Лист 4 - Диаграмма деятельности функции масштабирования графа по ширине - А1
http://kstrizhov.github.io/10sem/4_diagramma_deyatelnosti_a1.pdf

Лист 5 - Результаты работы - А1
http://kstrizhov.github.io/10sem/5_results_a1.pdf

Штампы к 1 и 5 листу
http://kstrizhov.github.io/10sem/shtamp_1_5.pdf

Все листы одним файлом
http://kstrizhov.github.io/10sem/all_in_one.pdf

Исходники листов
http://kstrizhov.github.io/10sem/ishodniki_listov.rar

**Comment by kstrizhov** [comment]
@aurusov
Вы не смотрели еще ТЗ?

**Comment by aurusov** [comment]
:one: А1, Постановка задачи **[на печать]**
:two: А1, Диаграмма классов подсистемы визуализации поиска на графе пространства состояний **[на печать]**
:three: А1, Диаграмма последовательности работы подсистемы визуализации поиска на графе пространства состояний **[на печать]**
:four: А1, Диаграмма деятельности функции масштабирования графа по ширине **[на печать]**
:five: А1, Результаты работы **[на печать]**

Штампы на плакаты **[на печать]**

Записка **[на печать]**

**Comment by kstrizhov** [comment]
Так там же есть, в записке. Или то, что я написал, не годится?

**Comment by kstrizhov** [comment]
Там все до конца концептуального проектирования готово. В конце концептуального проектирования есть пункт про тесты, но я думаю там их оставлять или перенести в конец.

**Comment by aurusov** [comment]
https://github.com/kstrizhov/rdo-xtext/issues/11#issuecomment-109200872
Воспринял твой ответ как отсутствие ТЗ

**Comment by aurusov** [comment]
ТЗ
- ```Проектирование модуля визуализации поиска решения на графе состояний в РДО``` - какое нафиг проектирование ? Проект уже сдавать пора. И в том семестра такая же финя была.
- 3.3.1 Просто замени на это (кто же тебя пытает, когда ты такое пишешь)
```
- Построение графа в процессе моделирования
- Масштабирование
- Вписывание в экранную форму
- Работа в относительной системы координат
- Построение графа из дерева трассируемых объектов
```
- ```монитор с разрешением от 1280*1024 и выше``` - ты в таком разрешение работаешь с графом ?
- 3.6 - ok

**Comment by aurusov** [comment]
ТЗ
- ```Постановка задачи``` - из 4-х абзацев прямо сейчас можно удалить два и ничего не поменяется. Два других перепеши человеческим языком, читать же противно.

**Comment by kstrizhov** [comment]
> какое нафиг проектирование ?  Проект уже сдавать пора..

Вы же сами ответили в письме, что тему оставить такой же? Какую тогда лучше?

> Просто замени на это

Я пользуюсь примерами других записок, везде придерживаются такого стилия(

> ты в таком разрешение работаешь с графом ?

1366*768. Такие цифры принципиальны?

> из 4-х абзацев прямо сейчас можно удалить два и ничего не поменяется. 

Вы имеете в виду 1 и 3?

**Comment by aurusov** [comment]
> > какое нафиг проектирование ? Проект уже сдавать пора..
> 
> Вы же сами ответили в письме, что тему оставить такой же? Какую тогда лучше?

Я подписывал тебе тему, `Подсистема визуализации поиска решений на графе состояний в РДО`, отражено вот [тут](https://github.com/aurusov/aurusov.github.io/tree/master/diploma/2014/%D0%9F%D0%BE%D0%B4%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0%20%D0%B2%D0%B8%D0%B7%D1%83%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8%20%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0%20%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B9%20%D0%BD%D0%B0%20%D0%B3%D1%80%D0%B0%D1%84%D0%B5%20%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B9%20%D0%B2%20%D0%A0%D0%94%D0%9E%20-%20%D0%A1%D1%82%D1%80%D0%B8%D0%B6%D0%BE%D0%B2%20%D0%9A%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%20-%20%D0%A0%D0%9A9-92), к примеру, и [тут](https://github.com/aurusov/aurusov.github.io/blob/master/diploma/2014/%D0%9F%D0%BE%D0%B4%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0%20%D0%B2%D0%B8%D0%B7%D1%83%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8%20%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0%20%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B9%20%D0%BD%D0%B0%20%D0%B3%D1%80%D0%B0%D1%84%D0%B5%20%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B9%20%D0%B2%20%D0%A0%D0%94%D0%9E%20-%20%D0%A1%D1%82%D1%80%D0%B8%D0%B6%D0%BE%D0%B2%20%D0%9A%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%20-%20%D0%A0%D0%9A9-92/%D0%9B%D0%B8%D1%81%D1%82%D1%8B.pdf). Надеюсь, что и на титульнике записки тоже, но его сейчас не вижу. А этот бред я бы не подписал.

**Comment by aurusov** [comment]
> > Просто замени на это
> 
> Я пользуюсь примерами других записок, везде придерживаются такого стилия(

Теперь нет

**Comment by aurusov** [comment]
> 1366*768. Такие цифры принципиальны?

Принципиально не писать глупости, например, в виде формальных отписак. Уже лучше написать фразу - никаких специальных требований, чем писать разрешение монитора, которого уже физически сложно найти.

**Comment by aurusov** [comment]
> Вы имеете в виду 1 и 3?

Да

**Comment by kstrizhov** [comment]
Добавил 2 лист с диаграммой классов.

**Comment by kstrizhov** [comment]
Добавил 3 лист с диаграммой последовательностей.

**Comment by aurusov** [comment]
Отписался в итого

**Comment by kstrizhov** [comment]
> - Выдели цветом, какие классы ты разрабатывал сам или вносил изменения ? Лучше отдельным листом, не для печати
> - Название на листе и в твоей шапке отличаются. Приведи к одному

Сделал.

> - Что значит alt в правом нижнем ?
> - Что значит горизонтальная пунктирная внутри этого alt ?

Alt - от alternative, рамкой показываются альтернативные варианты. Горизонтальная пунктирная стрелка их разделяет.

**Comment by aurusov** [comment]
Отписался в итого

**Comment by kstrizhov** [comment]
Добавил 4 лист. Еще есть в голове мысль сделать вторую диаграмму деятельности, отобразить создание независимых потоков при обновлении графа в рилтайме (думаю примерно А2 получится). Остается лист постановки задачи и лист с результатами.

**Comment by aurusov** [comment]
> Еще есть в голове мысль сделать вторую диаграмму деятельности, отобразить создание независимых потоков при обновлении графа в рилтайме (думаю примерно А2 получится).

Тогда названия у обеих должны быть со смыслом, а не вообще, как сейчас.

**Comment by aurusov** [comment]
> Тогда названия у обеих должны быть со смыслом, а не вообще, как сейчас.

Перепутал с диаграммой последовательности, отбой

**Comment by kstrizhov** [comment]
> Выглядит неплохо. Какой размер шрифта ?

18

**Comment by kstrizhov** [comment]
> - Уж больно мелкий шрифт. Попробуй его увеличить, на листе есть пустое место.
> - Какой размер шрифта сейчас ? Какой удалось сделать ?

Ситуация аналогичная, я в inkscape все равно масштабирую изображение. В самом uml-тулзе поменял с 11 на 14. Но если с диаграммой деятельности я увеличивал, и в итоге получил 18 шрифт, то диаграмма классов получилась большой, и я уменьшаю, чтобы влезла в рамку.

Добавил 2 лист с измененным шрифтом.

**Comment by aurusov** [comment]
Шрифтом меньше 14 лучше не показывать. Твой ответ я не понял. Прошу переделать лист, чтобы там стало намного меньше пустого места, а шрифт достиг 14.

**Comment by kstrizhov** [comment]
Обновил 2 и 4 листы, теперь со шрифтами все должно быть в порядке.

**Comment by kstrizhov** [comment]
Что можно написать на листе постановки задачи для пункта "Построение графа в процессе моделирования" кроме того, что это наглядно показывает работу алгоритма А*?

Updated: и кроме реализации работы подсистемы в рамках независимого потока?

**Comment by aurusov** [comment]
А что изменилось на 4-ом ?

**Comment by aurusov** [comment]
> Что можно написать на листе постановки задачи для пункта "Построение графа в процессе моделирования" кроме того, что это наглядно показывает работу алгоритма А*?

Постановка задачи самый творческий лист, думай сам, предложи вариант.

> Updated: и кроме реализации работы подсистемы в рамках независимого потока?

Не понял про что. Если тебя интересует, что ты должен защищать, то это написано тут

> - 3.3.1 Просто замени на это (кто же тебя пытает, когда ты такое пишешь)
> 
> ```
> - Построение графа в процессе моделирования
> - Масштабирование
> - Вписывание в экранную форму
> - Работа в относительной системы координат
> - Построение графа из дерева трассируемых объектов
> ```

**Comment by kstrizhov** [comment]
> А что изменилось на 4-ом ?

Подписал стрелки у блоков ветвления. Со шрифтами там и раньше все было в порядке, 18.

> Постановка задачи самый творческий лист, думай сам, предложи вариант.

Конкретно про построение графа в процессе моделирования я придумал только 2 пункта:
1. наглядное представление работы алгоритма А*
2. реализация работы подсистемы в рамках отдельного потока

Причем мне кажется, что второй пункт вообще мало относится к задачам, которые надо было решить, реализовав эту фичу. Это скорее средство. Но других идей нет.

> Не понял про что. Если тебя интересует, что ты должен защищать, то это написано тут

Пункт updated тоже относился к построению на лету, я просто потом дописал вторую мысль.

**Comment by aurusov** [comment]
Обновил итого, жду два листа и исправленную записку.

**Comment by kstrizhov** [comment]
Добавил 1 лист (постановка задачи).

**Comment by aurusov** [comment]
ok

**Comment by kstrizhov** [comment]
Доделал записку, добавил лист результатов, сделал штампы к плакатам.

**Comment by aurusov** [comment]
Обновил итого

**Comment by kstrizhov** [comment]
> Какая будет скорость, если отключить автомасштабирование ? Т.е. сравни скорость с результатом прошлого семестра (пока только для меня, а не для листа)

Это тесты с отключенным автомасштабированием. Сейчас оно адекватно ведет себя, если запускать граф в процессе моделирования. Если запустить прогон в режиме "без анимации" и остановить на 10000 вершин, и потом построить граф, он странно ведет себя, и строится дольше. Мне нужно еще поотлаживать этот момент.

**Comment by aurusov** [comment]
Тогда какая скорость в режиме с анимацией ?

**Comment by aurusov** [comment]
Обновил итого

**Comment by kstrizhov** [comment]
> Тогда какая скорость в режиме с анимацией ?

В режиме с анимацией скорость такая же, как без, ведь он открывает граф, строит все вершины, записи которых уже считаны из бд, а дальше начинает достраивать на ходу.

Я отладился немного, чтобы автомасштабирование работало сразу при построении графа. Скорость для 5000 и 10000 такая же, для 20000 на секунду-полторы больше, для 30000 на две-две с половиной секунды, то есть время ожидания несильно, но растет. Тестов правда провел не очень много, по 2 на каждое контрольное значение, потому что для большого количества вершин затратно по времени ждать, пока промоделируется.

**Comment by kstrizhov** [comment]
Исправил записку.

**Comment by aurusov** [comment]
Хорошо, всё на печать. Подготовь материалы к публикации
- листы и штампы одним файлов в pdf
- исходники листов
- записка в pdf (есть)
- записка в оригинале (есть)

**Comment by kstrizhov** [comment]
> - исходники листов

Исходники тоже есть в репозитории. Выслать все архивом на почту?

Когда и где можно будет подписаться?

**Comment by aurusov** [comment]
> Исходники тоже есть в репозитории. Выслать все архивом на почту?

У меня нет ссылок на первые два пункта. Хочется закончить с этим сегодня.

> Когда и где можно будет подписаться?

Завтра в Яндексе, после 12:00.

**Comment by kstrizhov** [comment]
Добавил файл со всеми листаим и архив с исходниками.

Обновил pages, дал ссылки в начале таски.

**Comment by aurusov** [comment]
svg - это же не совсем исходники листов. В чем ты рисовал диаграммы ?

**Comment by kstrizhov** [comment]
В Visual Paradigm. Хорошо, сейчас прикреплю к архиву.

**Comment by kstrizhov** [comment]
Сделал.

**Comment by aurusov** [comment]
Выложил http://aurusov.github.io/rdo_diploma/

**Comment by aurusov** [comment]
Закрывай задачу
